### ISSUE TITLE
Add emoji support to the yaml text editor

### ISSUE THREAD

**Issue by afbjorklund** [afbjorklund/lima-gui#17]
Some of the example files are using emojis, like "green circle":

```yaml
# CPUs: if you see performance issues, try limiting cpus to 1.
# 🟢 Builtin default: 4
cpus: null

# Memory size
# 🟢 Builtin default: "4GiB"
memory: null

# Disk size
# 🟢 Builtin default: "100GiB"
disk: null
```

But these codepoints are not currently supported by the text editor:

![lima-gui-yaml-editor](https://user-images.githubusercontent.com/10364051/170872105-81db93be-38e0-4de8-b280-58395343a706.png)

----

See e.g. https://unicode.org/emoji/charts/full-emoji-list.html#1f7e2

There is support for this in https://github.com/raven-worx/qrwemoticons

* https://www.openmoji.org/ ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/#))

* https://www.openmoji.org/library/emoji-1F7E2/
