### ISSUE TITLE
The parameters in "Quick Start" are not implemented yet (grayed out)

### ISSUE THREAD

**Issue by afbjorklund** [afbjorklund/lima-gui#6]
Use the "Edit YAML" as a workaround, for now. See "default.yaml" for options

https://github.com/lima-vm/lima/blob/master/pkg/limayaml/default.yaml

```yaml
# Arch: "default", "x86_64", "aarch64".
# Default: "default" (corresponds to the host architecture)
arch: "default"

# CPUs: if you see performance issues, try limiting cpus to 1.
# Default: 4
cpus: 4

# Memory size
# Default: "4GiB"
memory: "4GiB"

# Disk size
# Default: "100GiB"
disk: "100GiB"
```
